name = "azure-quiz-cf"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# فایل‌های فرانت
[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

# بعد از ساخت D1، database_id را جایگزین کنید
[[d1_databases]]
binding = "DB"
database_name = "azure-quiz-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"

[vars]
ADMIN_NATIONAL_IDS = "1274829860"
# SECRET_KEY را در داشبورد به صورت Secret بگذارید؛ برای dev:
# SECRET_KEY در wrangler secret put SECRET_KEY
